package questao05.Enums;

public enum LOCAIS {
	DRIVETHRUUFRPE, DRIVETHRUGERALDAO, CENTRODEVACINACAOPARQUEDEEXPOSICAO,
	CENTRODEVACINACAOCOMPAZARIANOSUASSUNA, DRIVETHRUPARQUEDEEXPOSICAO, DRIVETHRUARRUDA;
}
